name: musicpod
description: Ubuntu music, radio and podcast player.

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  audio_service: ^0.18.12
  basic_utils: ^5.6.1
  cached_network_image: ^3.3.0
  collection: ^1.17.0
  connectivity_plus: ^5.0.1
  cupertino_icons: ^1.0.6
  desktop_notifications: ^0.6.3
  file: ^7.0.0
  file_selector: ^1.0.0
  file_selector_linux: ^0.9.2
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  flutter_html: ^3.0.0-beta.2
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.15
  flutter_tabler_icons: ^1.7.0
  gtk: ^2.1.0
  handy_window: ^0.3.1
  intl: ^0.18.0
  media_kit: ^1.1.10
  media_kit_libs_video: ^1.0.4
  media_kit_video: ^1.2.4
  metadata_god: ^0.5.2+1
  mime: ^1.0.4
  mime_type: ^1.0.0
  mpris_service:
    git:
      url: https://github.com/alexmercerind/mpris_service
      ref: 3a4a721
  palette_generator: ^0.3.3+2
  path: ^1.8.3
  path_provider: ^2.1.1
  podcast_search: ^0.6.0
  provider: ^6.0.5
  radio_browser_api: ^1.0.0
  safe_change_notifier: ^0.3.0
  shimmer: ^3.0.0
  smtc_windows: ^0.1.1
  stream_transform: ^2.1.0
  ubuntu_service: ^0.3.0
  url_launcher: ^6.1.10
  xdg_directories: ^1.0.0
  yaru: ^1.2.0
  yaru_icons: ^2.2.2
  yaru_widgets: ^3.3.1
  yaru_window: ^0.1.3
  yaru_window_linux: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - snap/gui/musicpod.png
    - assets/contributors.md
