name: musicpod
description: Ubuntu music, radio and podcast player.
version: 2.14.0+1340

publish_to: "none"

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  audio_metadata_reader: ^1.4.2
  audio_service: ^0.18.18
  audio_service_mpris:
    git:
      url: https://github.com/Feichtmeier/audio-service-mpris
      ref: ad6f743b73e320670449026fa1852d9978438bb9
  basic_utils: ^5.8.2
  blur: ^4.0.2
  cached_network_image: ^3.4.1
  chinese_font_library: ^1.2.0
  collection: ^1.19.1
  cupertino_icons: ^1.0.8
  dio: ^5.9.1
  file: ^7.0.1
  file_picker: ^10.3.10
  file_selector: ^1.1.0
  file_selector_linux: ^0.9.4
  flex_color_picker: ^3.8.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_discord_rpc: ^1.1.0
  flutter_it: 2.1.1
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.7+1
  flutter_tabler_icons: ^1.43.0
  flutter_widget_from_html_core: ^0.17.0
  future_loading_dialog: ^0.3.0
  genius_lyrics: ^1.0.1
  github: ^9.25.0
  gtk: ^2.1.0
  handy_window: ^0.4.0
  internet_connection_checker_plus: ^2.9.1+2
  intl: ^0.20.2
  lastfm: ^0.0.6
  listenbrainz_dart: ^0.0.4
  local_notifier: ^0.1.6
  lrc: ^1.0.2
  m3u_parser_nullsafe: ^1.0.3
  media_kit:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: 7d1e3f8116abce740bdf83dc5e85f37e89436db5
      path: ./media_kit
  media_kit_libs_video:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: 7d1e3f8116abce740bdf83dc5e85f37e89436db5
      path: ./libs/universal/media_kit_libs_video
  media_kit_video:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: 7d1e3f8116abce740bdf83dc5e85f37e89436db5
      path: ./media_kit_video
  mime: ^2.0.0
  mockito: ^5.6.3
  opml: ^0.4.0
  package_info_plus: ^8.3.1
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  phoenix_theme:
    git:
      url: https://github.com/ubuntu-flutter-community/phoenix_theme
      ref: 7d22aba2841e522bf4c140e60e4a60f33c8f5aa6
  pls: ^1.1.0
  podcast_search: ^0.7.13
  radio_browser_api: ^2.0.0+1
  reorderableitemsview: ^2.0.1
  safe_change_notifier: ^0.4.0+1
  scroll_to_index: ^3.0.1
  shared_preferences: ^2.5.4
  shimmer: ^3.0.0
  smtc_windows: ^1.1.0
  super_drag_and_drop: ^0.9.1
  synchronized: ^3.4.0
  system_theme: ^3.2.0
  url_launcher: ^6.3.2
  watcher: ^1.2.1
  waveform_visualizer: ^1.0.0
  win32: ^5.15.0
  window_manager: ^0.5.1
  xdg_directories: ^1.1.0
  yaru: ^9.0.1
  yaru_window: ^0.2.2
  yaru_window_linux: ^0.2.2

dev_dependencies:
  build_runner: ^2.11.0
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: true
  ios: false
  min_sdk_android: 23
  image_path: "assets/icon.png"
  adaptive_icon_foreground: "assets/monochrome.png"
  adaptive_icon_monochrome: "assets/monochrome.png"
  adaptive_icon_background: "#ed3c63"
  image_path_android: "assets/flat_icon.png"
  adaptive_icon_foreground_inset: 20

flutter:
  generate: true
  uses-material-design: true
  assets:
    - snap/gui/musicpod.png
    - assets/images/listenbrainz-icon.png
    - assets/images/media-optical.png
    - assets/images/tray_icon.ico
    - assets/images/tray_icon.png
    - assets/icon.png
    - CHANGELOG.md

dependency_overrides:
  media_kit_libs_android_video:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: 7d1e3f8116abce740bdf83dc5e85f37e89436db5
      path: ./libs/android/media_kit_libs_android_video
  media_kit_libs_ios_video:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: 7d1e3f8116abce740bdf83dc5e85f37e89436db5
      path: ./libs/ios/media_kit_libs_ios_video
  media_kit_libs_linux:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: 7d1e3f8116abce740bdf83dc5e85f37e89436db5
      path: ./libs/linux/media_kit_libs_linux
  media_kit_libs_macos_video:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: 7d1e3f8116abce740bdf83dc5e85f37e89436db5
      path: ./libs/macos/media_kit_libs_macos_video
  media_kit_libs_ohos:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: 7d1e3f8116abce740bdf83dc5e85f37e89436db5
      path: ./libs/ohos/media_kit_libs_ohos
  media_kit_libs_windows_video:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: 7d1e3f8116abce740bdf83dc5e85f37e89436db5
      path: ./libs/windows/media_kit_libs_windows_video
