name: musicpod
description: Ubuntu music, radio and podcast player.
version: 2.12.0+1338

publish_to: "none"

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.2"

dependencies:
  animated_emoji: ^3.1.0
  audio_metadata_reader: ^1.4.1
  audio_service: ^0.18.12
  audio_service_mpris:
    git:
      url: https://github.com/Feichtmeier/audio-service-mpris
      ref: ad6f743b73e320670449026fa1852d9978438bb9
  basic_utils: ^5.7.0
  blur: ^4.0.2
  cached_network_image: ^3.4.1
  collection: ^1.18.0
  connectivity_plus: ^6.0.5
  cupertino_icons: ^1.0.8
  desktop_notifications: ^0.6.3
  dio: ^5.7.0
  file: ^7.0.0
  file_picker: ^10.0.0
  file_selector: ^1.0.3
  file_selector_linux: ^0.9.2
  flex_color_picker: ^3.7.1
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_discord_rpc: ^1.0.0
  flutter_html: ^3.0.0-beta.2
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.3
  flutter_tabler_icons: ^1.41.0
  github: ^9.24.0
  gtk: ^2.1.0
  handy_window: ^0.4.0
  html: ^0.15.4
  intl: ^0.20.2
  lastfm: ^0.0.6
  listenbrainz_dart: ^0.0.4
  m3u_parser_nullsafe: ^1.0.3
  media_kit:
    git:
      url: https://github.com/media-kit/media-kit
      path: media_kit
  media_kit_libs_video:
    git:
      url: https://github.com/media-kit/media-kit
      path: libs/universal/media_kit_libs_video
  media_kit_video:
    git:
      url: https://github.com/media-kit/media-kit
      path: media_kit_video
  mime: ^2.0.0
  mockito: ^5.4.4
  opml: ^0.4.0
  package_info_plus: ^8.0.0
  palette_generator: ^0.3.3+3
  path: ^1.9.0
  path_provider: ^2.1.2
  permission_handler: ^12.0.0+1
  phoenix_theme:
    git:
      url: https://github.com/ubuntu-flutter-community/phoenix_theme
      ref: 7d22aba2841e522bf4c140e60e4a60f33c8f5aa6
  pls: ^1.1.0
  podcast_search: ^0.7.3
  radio_browser_api: ^2.0.0
  reorderableitemsview: ^2.0.1
  safe_change_notifier: ^0.4.0
  scroll_to_index: ^3.0.1
  shared_preferences: ^2.3.1
  shimmer: ^3.0.0
  smtc_windows: ^1.0.0
  super_drag_and_drop: ^0.9.1
  synchronized: ^3.3.1
  system_theme: ^3.0.0
  url_launcher: ^6.3.0
  watch_it: ^1.5.0
  watcher: ^1.1.1
  win32: ^5.5.4
  window_manager: ^0.4.2
  xdg_directories: ^1.0.4
  yaru:
    git:
      url: https://github.com/ubuntu/yaru.dart
      ref: 8103703947b001fa2abe03f0a23261d397cee1c7
  yaru_window: ^0.2.1+1
  yaru_window_linux: ^0.2.0+1

dev_dependencies:
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: true
  ios: false
  min_sdk_android: 23
  image_path: "assets/icon.png"
  adaptive_icon_background: "assets/icon.png"
  adaptive_icon_foreground: "assets/icon.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - snap/gui/musicpod.png
    - assets/images/listenbrainz-icon.png
    - assets/images/media-optical.png
    - assets/images/tray_icon.ico
    - assets/images/tray_icon.png
    - assets/icon.png
    - CHANGELOG.md

dependency_overrides:
  intl: ^0.20.2
  media_kit:
    git:
      url: https://github.com/media-kit/media-kit
      path: media_kit
      ref: d544e1c52db47a45097a8332a862687c832359d9
  media_kit_libs_video:
    git:
      url: https://github.com/media-kit/media-kit
      path: libs/universal/media_kit_libs_video
      ref: d544e1c52db47a45097a8332a862687c832359d9
  media_kit_video:
    git:
      url: https://github.com/media-kit/media-kit
      path: media_kit_video
      ref: d544e1c52db47a45097a8332a862687c832359d9
