name: musicpod
description: Ubuntu music, radio and podcast player.

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  collection: ^1.17.0
  connectivity_plus: ^4.0.1
  desktop_notifications: ^0.6.3
  file_selector: ^1.0.0
  file_selector_linux: ^0.9.2
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-beta.2
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.15
  handy_window: ^0.3.1
  intl: ^0.18.0
  media_kit: ^1.0.2
  media_kit_libs_linux: ^1.0.2
  flutter_media_metadata:
    git:
      url: https://github.com/aleksrutins/flutter_media_metadata
  mime_type: ^1.0.0
  mpris_service:
    git:
      url: https://github.com/alexmercerind/mpris_service
      ref: 3a4a721
  palette_generator: ^0.3.3+2
  path: ^1.8.2
  podcast_search: ^0.6.0
  provider: ^6.0.5
  radio_browser_api: ^1.0.0
  safe_change_notifier: ^0.3.0
  shimmer: ^3.0.0
  ubuntu_service: ^0.2.0
  url_launcher: ^6.1.10
  xdg_directories: ^1.0.0
  yaru: ^0.9.0
  yaru_icons: ^2.1.0
  yaru_widgets: ^2.6.0
  yaru_window: ^0.1.3
  yaru_window_linux: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - snap/gui/musicpod.png
    - assets/contributors.md

dependency_overrides:
  yaru_icons: ^2.1.0
