name: musicpod
description: Ubuntu music, radio and podcast player.

publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  collection: ^1.17.0
  connectivity_plus: ^3.0.3
  desktop_notifications: ^0.6.3
  file_selector: ^0.9.2+3
  file_selector_linux: ^0.9.1+1
  flutter:
    sdk: flutter
  flutter_html: ^2.2.1
  flutter_localizations:
    sdk: flutter
  handy_window: ^0.3.1
  http: ^0.13.5
  intl: ^0.17.0
  media_kit: 0.0.1
  media_kit_libs_linux: ^1.0.0
  metadata_god: ^0.3.2
  mime_type: ^1.0.0
  mpris_service:
    git: https://github.com/alexmercerind/mpris_service
  palette_generator: ^0.3.3+2
  path: ^1.8.2
  podcast_search: 0.5.5
  provider: ^6.0.5
  safe_change_notifier: ^0.2.0
  shimmer: ^2.0.0
  ubuntu_service: ^0.2.0
  url_launcher: ^6.1.10
  xdg_directories: ^1.0.0
  yaru: ^0.7.0
  yaru_icons: ^1.0.4
  yaru_widgets: ^2.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
   generate: true
   uses-material-design: true

dependency_overrides:
  xml: ^6.2.2