name: music
description: Ubuntu music, radio and podcast player.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  audioplayers: ^3.0.1
  audioplayers_linux: ^1.0.4
  file_selector: ^0.9.2+3
  file_selector_linux: ^0.9.1+1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  handy_window: ^0.3.1
  http: ^0.13.5
  intl: ^0.17.0
  provider: ^6.0.5
  safe_change_notifier: ^0.2.0
  yaru: ^0.5.5
  yaru_icons: ^1.0.3
  yaru_widgets: ^2.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
   generate: true
